import { WebsiteHeader } from '@/components/WebsiteHeader';
import { ServiceGrid } from '@/components/ServiceGrid';
import { RevnciaLogo } from "@/components/RevnciaLogo";
import { solutionPillars } from '@/lib/services';
import './globals.css';


export default function Home(){return <main><WebsiteHeader/><section className="rv-hero"><div className="rv-hero-copy"><span className="rv-kicker">REVNCIA • DIGITAL TRANSFORMATION & PUBLIC IMPACT</span><h1>Transform organizations.<br/><span>Automate operations.</span><br/>Create measurable impact.</h1><p>REVNCIA brings AI, automation, cloud, cybersecurity, software, data and public-impact capabilities together into one connected operating model.</p><div className="rv-actions"><a className="rv-btn rv-btn-primary" href="/get-started">Explore REVNCIA</a><a className="rv-btn rv-btn-secondary" href="/os">Open REVNCIA OS</a></div><div className="rv-proof"><div><strong>AI</strong><span>Intelligence</span></div><div><strong>∞</strong><span>Connected Services</span></div><div><strong>24/7</strong><span>Digital Operations</span></div></div></div><div className="rv-hero-visual"><div className="rv-orbit"><div className="rv-orbit-core">REVNCIA<br/><small>AI ECOSYSTEM</small></div><span className="rv-node n1">AI</span><span className="rv-node n2">CLOUD</span><span className="rv-node n3">DATA</span><span className="rv-node n4">SECURITY</span></div></div></section><section id="solutions" className="rv-section rv-section-soft"><div className="rv-section-head"><span className="rv-kicker">ONE PLATFORM. MANY OUTCOMES.</span><h2>Solutions that move from strategy to execution.</h2></div><div className="rv-solution-grid">{solutionPillars.map((s,i)=><article className="rv-solution-card" key={s.id}><span className="rv-number">0{i+1}</span><span className="rv-card-label">{s.category}</span><h3>{s.name}</h3><p>{s.description}</p><div className="rv-outcome"><span>OUTCOME</span><strong>{s.outcome}</strong></div><a href={`/solutions/${s.id}`}>Explore solution →</a></article>)}</div></section><ServiceGrid/><section id="ai" className="rv-feature"><div><span className="rv-kicker">REVNCIA OS</span><h2>A clean operating system for intelligent transformation.</h2><p>Give every organization a unified workspace for AI Core, services, agents, workflows, knowledge, integrations, projects, analytics, governance and security.</p><a className="rv-btn rv-btn-primary" href="/os">Enter REVNCIA OS</a></div><div className="rv-os-preview"><div className="preview-top">REVNCIA OS <span>● Operational</span></div><div className="preview-metrics"><b>AI Core<small>Ready</small></b><b>Agents<small>18 active</small></b><b>Workflows<small>42 running</small></b><b>Projects<small>12 active</small></b></div><div className="preview-bars"><i/><i/><i/><i/><i/></div></div></section><footer className="rv-footer" id="company"><RevnciaLogo/><p>REVNCIA — A Digital Transformation & Public Impact Company.</p></footer></main>}

