export type Offering = {
  slug: string;
  n: string;
  name: string;
  title: string;
  stage: "1" | "2" | "3" | "4" | "5";
  group: string;
  summary: string;
  body: string;
  capabilities: string[];
  image?: string;
  note?: string;
};

export const offerings: Offering[] = [
  {
    slug: "ai-platform",
    n: "01",
    name: "REVNCIA AI Platform",
    title: "One governed door for every AI your staff use",
    stage: "2",
    group: "Platform",
    summary:
      "Your people stop buying random chatbots. They sign in once, use approved models, stay inside cost and access rules, and leave a log a board can read. Built for IT, risk, and operations owners who must explain AI — not only demo it.",
    body: "You receive an AI Gateway: multi-model routing, cost-aware selection, token and usage meters, named accounts, permissions, guardrails, evaluation, logging, observability, and analytics. Knowledge, memory, and context sit beside the assistants you commission — employee, executive, customer, department, research, and decision-support. Specialized agents can cover sales, service, HR, finance, operations, procurement, compliance, research, administration, projects, and executive work. After go-live your owner sees who asked what and what it cost; unused personal ChatGPT logins are out of scope unless you connect them yourself. We do not publish a token price list or promise every commercial model on earth.",
    capabilities: [
      "One gateway instead of personal chatbot logins",
      "Cost envelopes your owner can read",
      "Named accounts, roles, and permissions",
      "Logs, evaluation, and a trail you can show",
      "Knowledge, memory, and context you authorise",
      "Employee, customer, and department assistants",
      "Agents that stay inside the same rules",
    ],
  },
  {
    slug: "customer-operations",
    n: "02",
    name: "AI Customer Service",
    title: "Customers get answers on every channel — your team takes the hard cases",
    stage: "1",
    group: "Revenue engine",
    image: "/images/ops-room.png",
    summary:
      "Website, WhatsApp, Messenger, Instagram, email, voice, SMS, and mobile become one monthly service desk. Customers stop repeating their story. Your people only pick up what the assistant cannot finish.",
    body: "You receive omnichannel customer AI: questions, lead qualification, booking, order tracking, complaints, FAQ, onboarding, document collection, tickets, human escalation, follow-ups, and multilingual support. Channels include website chat, WhatsApp, Facebook Messenger, Instagram, email, Voice, SMS, and mobile apps. Who it helps: service managers, sales ops, and public counters that already lose nights and weekends. After go-live the platform is charged monthly per organisation — hours of cover are yours to set, not a 24/7 REVNCIA guarantee. We do not invent WhatsApp tokens or a public voice number. Scope is written in the statement of work.",
    capabilities: [
      "One desk across web, WhatsApp, social, email, and voice",
      "Qualification, booking, and order tracking customers can finish",
      "Complaints that become tickets with owners",
      "A path to a human when the case is hard",
      "Follow-ups and languages you approve",
    ],
  },
  {
    slug: "whatsapp-ai",
    n: "03",
    name: "WhatsApp AI Automation",
    title: "WhatsApp becomes a shared desk — not one person’s phone",
    stage: "1",
    group: "Revenue engine",
    image: "/images/scene-messaging.png",
    summary:
      "If you already sell or support on WhatsApp, chats become a system: bot, leads, support, scheduling, notices, documents, CRM, and a clean handoff. Customers message the number you already publish.",
    body: "You receive an AI chatbot on the WhatsApp Business identity you own — lead capture, support, appointment scheduling, payment and order notices, verification, document collection, follow-ups, campaigns you approve, human-agent handoff, CRM write-back, and analytics. Who it helps: retailers, clinics, campuses, and field teams whose WhatsApp lives on one employee’s phone. After go-live customers keep messaging your number; your team uses a shared inbox or CRM. You still need Meta / Cloud API approvals for your country. We do not issue secret tokens, WABA names, or spam campaigns. Message volume is a usage meter agreed in writing.",
    capabilities: [
      "A bot on the WhatsApp identity you own",
      "Leads, support, and scheduling in one thread",
      "Payment and order notices you authorise",
      "Documents into a ticket — then a human if needed",
      "CRM write-back and conversation analytics",
    ],
  },
  {
    slug: "voice-ai",
    n: "04",
    name: "REVNCIA Voice",
    title: "Callers reach a voice that books, answers, and hands off",
    stage: "1",
    group: "Revenue engine",
    image: "/images/scene-voice.png",
    summary:
      "Reception, sales, service, appointments, collections, information, and helpdesk — inbound and outbound — with a summary in CRM and a path to a person. Callers use the numbers you provide.",
    body: "You receive voice agents for roles you name: receptionist, sales, customer service, appointments, collections, information, helpdesk, or an internal assistant. Functions include incoming and outbound calls, booking, verification, lead qualification, FAQs, call summaries, CRM updates, escalation, and multilingual conversation where you supply approved phrasing. Who it helps: front desks that miss calls, after-hours lines, and teams whose notes never reach CRM. After go-live supervisors see transcripts and handoffs in the console or CRM in scope. Hours of cover are a configuration, not a 24/7 REVNCIA promise. We do not publish a public Voice number, invent a retention period, or replace licensed collections, medical, or legal decisions.",
    capabilities: [
      "Inbound and outbound on numbers you own or port",
      "Reception, sales, service, and booking roles you name",
      "Summaries and fields written into CRM",
      "Escalation when the caller asks or the agent is outside its rules",
      "Languages you approve — not a silent global claim",
    ],
  },
  {
    slug: "crm",
    n: "05",
    name: "CRM Transformation",
    title: "One customer record your sales and service teams actually open",
    stage: "1",
    group: "Systems",
    image: "/images/boardroom.png",
    summary:
      "We do not only install CRM. You get pipelines, follow-up, segmentation, analytics, and AI inside the system of record — so history is not in inboxes and people’s heads.",
    body: "You receive implementation, migration, customization, lead and customer management, sales pipelines, segmentation, customer analytics, automated follow-ups, marketing and sales automation, an AI sales assistant, an AI CRM assistant, and journey automation. Who it helps: sales, service, and public case teams who chase the same lead twice or cannot see what converts. After go-live named users log into your tenant; admin roles stay with people you name. Training and a handover pack are part of the facility. We do not print vendor partner badges or licence SKUs. Your CRM vendor still bills you unless a written resale deal says otherwise. Unattended money movement stays under your dual control.",
    capabilities: [
      "A CRM people open every day — not a shelf licence",
      "Pipelines, segmentation, and follow-up that do not depend on memory",
      "Analytics on which offers actually convert",
      "AI assistants inside the same record",
      "Handover and training so adoption is in scope",
    ],
  },
  {
    slug: "erp",
    n: "06",
    name: "ERP Transformation",
    title: "Finance, stock, and people on one backbone leadership can trust",
    stage: "3",
    group: "Systems",
    summary:
      "Month-end stops being a scramble of exports. You get the ERP domains you scoped — finance, HR, procurement, inventory, operations, sales, service, projects, assets, reporting — plus AI that helps people check exceptions.",
    body: "For larger organisations you receive the modules named in the statement of work, not a slogan that claims every module on day one. AI on top can include finance, procurement, HR, and operations assistants, forecasting, reporting, and anomaly detection. Who it helps: CFOs, controllers, and operations leads whose reports disagree. After go-live staff use role-based logins; money movement still needs the dual control you require. Long-term this can sit under REVNCIA Enterprise OS. We do not clean every historical spreadsheet unless data work is a line item. We do not claim we are your ERP vendor.",
    capabilities: [
      "The ERP domains you scoped — not a day-one slogan",
      "One version of finance, stock, and people",
      "AI that flags exceptions for a human to check",
      "Forecasts and reports leadership can take to a board",
      "Role-based access so a clerk and a director do not share a password",
    ],
  },
  {
    slug: "process-automation",
    n: "07",
    name: "Business Process Automation",
    title: "Approvals, invoices, and onboarding stop waiting on one person",
    stage: "1",
    group: "Automation",
    summary:
      "We map how work actually happens, then move it from paper to digital to automated to AI-assisted. New staff stop learning unofficial workarounds.",
    body: "You receive process discovery and programmes such as invoice processing, employee and customer onboarding, leave, purchase requests, approvals, reporting, document processing, email workflows, CRM updates, compliance workflows, and internal communications. Who it helps: operations and admin leads whose simple approvals wait days because someone is travelling. After go-live the process lives in a system with an owner — not a habit. We automate what you scoped. We do not promise to remove every human judgement, and we do not invent an SLA for cycle time unless a later contract states one.",
    capabilities: [
      "A map of how work really happens today",
      "Invoices, onboarding, leave, and purchase requests that move without retyping",
      "Approvals with a trail — who signed, and when",
      "Documents, email, and CRM on the same path",
      "Compliance steps that are not optional folklore",
    ],
  },
  {
    slug: "document-intelligence",
    n: "08",
    name: "AI Document Intelligence",
    title: "Ask what you promised — across thousands of files",
    stage: "1",
    group: "Intelligence",
    image: "/images/scene-knowledge.png",
    summary:
      "Contracts, invoices, forms, and PDFs become a question you can ask — with citations back to the file. Legal and finance teams stop searching cupboards.",
    body: "You receive PDF processing, contract analysis, invoice extraction, form processing, classification, data extraction, summarisation, search, comparison, risk identification, and knowledge-base creation. You can ask what obligations exist under a corpus you designate. Who it helps: legal, finance, records, and case teams drowning in unread files. After go-live staff search or chat with the same roles as your files; high-risk documents go to a human review queue. This is not legal advice, a court-ready opinion, or a promise of 100% extraction accuracy on every scan. Medical diagnosis from clinical notes is out of scope unless a specialist engagement says otherwise.",
    capabilities: [
      "PDFs, contracts, invoices, and forms you can search",
      "Fields extracted into finance or case systems when scoped",
      "Obligation questions with a citation back to the file",
      "Risk flags a person can review",
      "A knowledge base built from sources you approve",
    ],
  },
  {
    slug: "knowledge-ai",
    n: "09",
    name: "Enterprise Knowledge AI",
    title: "Staff get the authorised answer — not a hallway rumour",
    stage: "2",
    group: "Intelligence",
    summary:
      "Policies, SOPs, documents, CRM, ERP, mail, and sites connect under access control. Employees ask a policy question and see only what their role may see.",
    body: "You receive a private organisational knowledge system connecting documents, policies, SOPs, databases, websites, CRM, ERP, email, and internal knowledge you authorise. Who it helps: HR, operations, and public officers who answer the same policy question every week — and new hires who cannot find how work is supposed to be done. After go-live answers are cited from authorised sources; a contractor should not see the board pack. Sensitive files should not be pasted into public chat tools. We do not claim the assistant replaces your legal or policy owner. Connectors run only when you authorise them.",
    capabilities: [
      "Policies and SOPs staff can ask in ordinary language",
      "CRM, ERP, and mail only where you connect them",
      "Role-based retrieval — not one open pile",
      "Cited answers you can check",
      "A stop on pasting private files into public AI tools",
    ],
  },
  {
    slug: "intelligence",
    n: "10",
    name: "AI Analytics & Decision Intelligence",
    title: "Leaders see what is about to break — not last month’s dashboard",
    stage: "2",
    group: "Intelligence",
    summary:
      "Forecasts, KPIs, anomalies, scenarios, and decision-support — with an explanation, not an unexplained score. Built for executives who cannot wait for a weekly pack.",
    body: "You receive business intelligence, predictive analytics, AI-generated reports, executive dashboards, forecasting, risk and trend detection, performance analysis, KPI monitoring, anomaly detection, scenario analysis, and decision-support. Who it helps: leadership teams who argue from gut feel because forecasts are missing. After go-live owners watch the measures you agreed to collect. Example charts are not a quote or a guaranteed accuracy number. Models are documented and can be retired when they no longer earn their place.",
    capabilities: [
      "Forecasts and KPIs on data you authorise",
      "Anomaly and risk signals before the month is lost",
      "Executive reports that do not take a week to build",
      "Scenario analysis for a decision, not a slide dump",
      "Explanations you can take to a meeting",
    ],
  },
  {
    slug: "cybersecurity",
    n: "11",
    name: "Cybersecurity & AI Security",
    title: "Identity, access, and AI-use rules you can show a board",
    stage: "3",
    group: "Trust",
    note: "We start with digital-security implementation and partner with specialists for advanced security. We do not present REVNCIA as a full cybersecurity firm.",
    summary:
      "Assessments, identity, access, AI security, monitoring, audit logs, vulnerability management, governance, and incident workflows. Advanced testing and deep incident retainers are done with specialist partners.",
    body: "You can receive security assessments, identity management, access control, role-based permissions, AI security, data protection, security monitoring, audit logging, vulnerability management, security policies, AI governance, and incident-response workflows. Who it helps: enterprise and public owners who share logins “just this once” or cannot tell an auditor who changed what. After go-live you have rules for AI use and a trail. Honest limit: REVNCIA is not a complete cybersecurity practice on day one. We do not invent certifications we do not hold. Penetration testing, SOC retainers, and deep forensics are partner work unless a later contract says otherwise.",
    capabilities: [
      "Named identity and least-privilege access",
      "Rules for how staff may use AI with customer data",
      "Monitoring and audit logs a board can ask for",
      "Policies and incident workflows you own",
      "A clear line: we implement; specialists take advanced cyber",
    ],
  },
  {
    slug: "data-transformation",
    n: "12",
    name: "Data Transformation",
    title: "Reports and AI stop arguing because the data is clean",
    stage: "3",
    group: "Infrastructure",
    image: "/images/scene-data.png",
    summary:
      "Integration, cleaning, migration, warehouses, pipelines, APIs, master data, governance, and visualization — so CRM, ERP, and AI share one customer or product record.",
    body: "You receive data integration, cleaning, migration, database modernization, warehouses, pipelines, API integration, master-data management, data governance, visualization, and AI-ready infrastructure. Who it helps: teams whose reports disagree because names and codes were never cleaned, and AI projects that stall because the data is not ready. After go-live someone you name owns the master record. We do not promise to clean every historical spreadsheet unless that work is a line item. We do not invent a public data dump.",
    capabilities: [
      "Integration and cleaning so reports stop conflicting",
      "Warehouses and pipelines your analysts can use",
      "A master customer or product record with an owner",
      "Governance so the next migration does not copy the old mess",
      "Data that is ready for AI — not a side experiment",
    ],
  },
  {
    slug: "cloud",
    n: "13",
    name: "Cloud Transformation",
    title: "Leave fragile servers — with backup, cost watch, and a recovery path",
    stage: "3",
    group: "Infrastructure",
    summary:
      "Strategy, migration, modernization, architecture, automation, backup, disaster recovery, monitoring, and cost optimization. Later this can become REVNCIA Cloud Operations.",
    body: "You receive help to move from legacy systems: cloud strategy, migration, application modernization, architecture, infrastructure automation, backup, disaster recovery, monitoring, and cost optimization. Who it helps: owners whose old servers fail and whose backups were never tested, or whose cloud bills have no owner. After go-live you have a recovery path written in the programme — not a fake status-page URL we invent. We do not publish a five-minute SLA or a 24/7 network operations centre unless a later contract says so. Cost envelopes are a conversation, not a silent surprise.",
    capabilities: [
      "A written move off servers that fail without warning",
      "Backup and disaster recovery you can actually test",
      "Monitoring and a cost owner",
      "Modernization of the apps you name",
      "No invented 24/7 SLA unless a later contract says so",
    ],
  },
  {
    slug: "software",
    n: "14",
    name: "Software Development",
    title: "Portals and apps so people finish the job on a screen",
    stage: "3",
    group: "Build",
    summary:
      "When a package is the wrong shape, we build enterprise, customer, and government portals, SaaS, dashboards, mobile field and citizen apps, APIs, and identity — so staff stop using paper beside the tool.",
    body: "You receive web systems (enterprise, customer, and government portals, SaaS platforms, dashboards, internal applications), mobile (customer, employee, field-service, and government service apps), and backend (APIs, microservices, databases, authentication, integrations). Who it helps: organisations whose off-the-shelf tools almost fit, so people keep clipboards. After go-live you own the accounts and the runbook in the handover. We build what is in the statement of work. We do not sell a generic “app factory” with a headline price. Every new need should not become another disconnected app — integrations are part of the design.",
    capabilities: [
      "Portals citizens or customers can finish a task in",
      "Internal dashboards staff actually use",
      "Mobile for field and citizen work",
      "APIs and identity so the next system can connect",
      "A handover — not a black box you cannot run",
    ],
  },
  {
    slug: "integrations",
    n: "15",
    name: "API & Integration Services",
    title: "The systems you already pay for start talking to each other",
    stage: "3",
    group: "Build",
    summary:
      "CRM to ERP, WhatsApp to CRM, accounting to ERP, website to CRM, AI to data and documents, payments to finance, government systems to citizen services. Staff stop copy-pasting.",
    body: "You receive connections such as CRM↔ERP, CRM↔WhatsApp, ERP↔accounting, website↔CRM, AI to databases, documents, email, and workflow, payments to ERP, and government systems to citizen services. Who it helps: teams whose week stops when one export breaks, or whose AI cannot help because it is not connected to live records. After go-live integrations are documented and monitored for the systems listed in the programme. We do not claim every vendor API on earth. A single failure should not take down the operation — fallbacks are designed, not hoped for.",
    capabilities: [
      "CRM, ERP, and accounting share one flow",
      "WhatsApp and the website write into the same record",
      "AI reads live data — not a weekly spreadsheet",
      "Payments and public systems connected when scoped",
      "Documented connections your operator can restart",
    ],
  },
  {
    slug: "government",
    n: "16",
    name: "Government Digital Transformation",
    title: "Citizens see status and book help — offices keep a file they can defend",
    stage: "4",
    group: "Public impact",
    image: "/images/scene-civic.png",
    summary:
      "Municipal, state, federal, and public authorities: citizen assistants, portals, complaints, cases, appointments, notifications, multilingual support, and measures you choose to publish — people served, time, access, resolution.",
    body: "You receive citizen services (AI assistants, digital portals, complaint and case management, appointments, notifications, multilingual support) and operations (workflow automation, document management, internal AI, data platforms, analytics, digital identity integrations when allowed, reporting, case processing). Public impact is measured only on the numbers you agree to collect. Who it helps: agencies whose citizens queue, call, and still do not know case status. After go-live the public uses the URL, kiosk, or number you publish; officers sign in with your identity system. REVNCIA does not act as a government, issue benefits, or deny a right without a human statutory path. Appeal and review stay yours.",
    capabilities: [
      "A status a citizen can check without calling twice",
      "Complaints and cases with an auditable file",
      "Appointments and notices on the channel in scope",
      "Officer copilots that leave a record",
      "Impact measures you choose — not invented KPIs",
    ],
  },
  {
    slug: "education",
    n: "17",
    name: "Education Transformation",
    title: "Parents, students, and teachers get answers so staff can teach",
    stage: "4",
    group: "Public impact",
    image: "/images/civic.png",
    summary:
      "Schools, universities, training houses, and education departments: student and teacher assistants, admissions, attendance, parent communication, learning analytics, and administration — not a replacement for teaching.",
    body: "You receive AI student and teacher assistants, admissions automation, student support, attendance, parent communication, learning analytics, administrative automation, document automation, career guidance, and institutional analytics. Who it helps: registrars and heads whose admissions and attendance eat every day, and parents who only hear from the school when something is wrong. After go-live families use the portal or channel you publish; staff keep the decisions that must stay human (discipline, grades where policy requires it). We do not sell a clinical or safeguarding product. Accessibility work is scoped, not a badge we invent.",
    capabilities: [
      "Admissions and attendance that do not eat the whole day",
      "Parent messages that are not only bad news",
      "Student and teacher assistants grounded in your materials",
      "Analytics that flag who needs help early",
      "Admin and documents so teachers can teach",
    ],
  },
  {
    slug: "healthcare",
    n: "18",
    name: "Healthcare Digital Transformation",
    title: "Appointments, reminders, and admin — not a clinical product",
    stage: "4",
    group: "Verticals",
    note: "Healthcare programmes require strong privacy, security, compliance processes, and appropriate specialist expertise. We do not diagnose, treat, or prescribe.",
    summary:
      "Patient communication, appointment automation, administrative AI, documents, portals, workflows, analytics, and call-centre AI — privacy first. Clinical care stays with clinicians.",
    body: "You can receive patient communication, appointment automation, administrative AI, document processing, patient portals, workflow automation, analytics, and call-center AI. Who it helps: front-office and call teams drowning in forms while patients miss appointments because reminders are manual. After go-live reminders and portals run on the hours you set; clinicians still own diagnosis and treatment. Honest limit: this is administrative and communication work. We do not diagnose, treat, prescribe, or replace a licensed clinician. Local law and specialists decide what may go live. Nothing we publish is medical advice.",
    capabilities: [
      "Reminders and booking so fewer patients miss the slot",
      "Admin AI and documents — not a clinical record we invent",
      "Portals and workflows the front office can run",
      "Call handling with a privacy-first design",
      "A written stop: care stays with clinicians",
    ],
  },
  {
    slug: "financial-services",
    n: "19",
    name: "Financial Services Transformation",
    title: "Faster onboarding and a full customer file — with a compliance trail",
    stage: "4",
    group: "Verticals",
    summary:
      "Banks, fintechs, microfinance, and insurers: service AI, employee copilots, documents, onboarding, CRM, knowledge, reporting, fraud and risk analytics, and compliance workflows.",
    body: "You receive customer service AI, employee copilots, document intelligence, workflow automation, fraud and risk analytics, compliance workflows, customer onboarding, CRM transformation, AI knowledge systems, and reporting automation. Who it helps: institutions whose onboarding takes weeks of paper, and teams who gather compliance evidence in a panic. After go-live staff see a fuller customer file; money movement and credit decisions stay under your licensed controls. We do not give investment advice. Fraud models are signals for your risk owners — not a guarantee against loss. Example charts are not a promised detection rate.",
    capabilities: [
      "Onboarding that does not take weeks of repeat visits",
      "Service AI and copilots on the customer file you authorise",
      "Documents and evidence you can show compliance",
      "Risk and fraud signals for your owners to act on",
      "Reporting that is not a last-minute scramble",
    ],
  },
  {
    slug: "retail",
    n: "20",
    name: "Retail & E-Commerce AI",
    title: "Shoppers get a reply, stock stays honest, WhatsApp sells with a record",
    stage: "4",
    group: "Verticals",
    summary:
      "Shopping assistants, recommendations, service, orders, inventory analytics, marketing, WhatsApp commerce, retention, and demand forecasting — so the site and the store share the same stock story.",
    body: "You receive AI shopping assistants, product recommendations, customer service, order management, inventory analytics, marketing automation, WhatsApp commerce, sales automation, customer retention, and demand forecasting. Who it helps: shops whose WhatsApp replies are slow or missing, and teams who stock out and overstock in the same week. After go-live shoppers use the channels you publish; repeat customers can be recognised in the CRM in scope. We do not invent a WhatsApp token. Demand forecasts are planning aids, not a guarantee of sell-through. Marketing here is a capability tied to CRM — not REVNCIA’s identity.",
    capabilities: [
      "A reply on web and WhatsApp — not silence",
      "Orders and inventory the store and the site share",
      "WhatsApp commerce on the number you own",
      "Retention so repeat customers are recognised",
      "Demand signals for planning — not a promised sell-through",
    ],
  },
  {
    slug: "marketing",
    n: "21",
    name: "Marketing Automation",
    title: "Campaigns that write back to CRM — a capability, not our name",
    stage: "1",
    group: "Growth",
    summary:
      "Content systems, leads, email, social, segmentation, campaign analytics, CRM automation, and personalised outreach. REVNCIA is an AI digital transformation and public-impact company. This is one facility — not the name on the door.",
    body: "You receive AI content systems, lead generation and qualification, email automation, social media automation, customer segmentation, campaign analytics, CRM automation, AI sales assistants, and personalised campaigns. Who it helps: teams whose campaigns have no link to CRM, so results are guessed, and the same people get the same message too often. After go-live leads and outcomes write back to the CRM in scope. Honest limit: marketing automation is not the company identity. We do not sell spam or unsolicited campaigns that break channel or local rules. We do not publish a guaranteed open rate or a PKR package.",
    capabilities: [
      "Content and campaigns that land in CRM",
      "Leads qualified before sales time is spent",
      "Segmentation so the same person is not messaged to death",
      "Analytics on what actually converted",
      "A clear limit: this is a capability, not who we are",
    ],
  },
  {
    slug: "sales-ai",
    n: "22",
    name: "AI Sales Systems",
    title: "Leads get followed, meetings get notes, renewals get a signal",
    stage: "1",
    group: "Growth",
    summary:
      "From first lead to retention: qualify, follow up, meet, propose, convert, and keep — with CRM updates, meeting summaries, and churn signals. The team spends time on deals, not typing.",
    body: "You receive a sales engine: Lead → Qualification → CRM → Follow-up → Meeting → Proposal → Conversion → Retention. AI can organise leads, qualify, send follow-ups, schedule meetings, prepare proposal drafts, update CRM, summarise meetings, flag opportunities, and surface churn risk. Who it helps: sales managers whose good leads wait while the team works the loudest inbox. After go-live the CRM is the system of record; humans still own the offer and the signature. Drafts are drafts. We do not promise a conversion rate. Churn signals are for your owner to act on — not a guarantee a customer stays.",
    capabilities: [
      "Leads organised and followed without depending on memory",
      "Meetings that leave notes in CRM",
      "Proposal drafts the team can finish",
      "Opportunity and churn signals for an owner",
      "Humans still own the price and the signature",
    ],
  },
  {
    slug: "hr-ai",
    n: "23",
    name: "AI HR",
    title: "Candidates move, staff self-serve, HR sees the workforce",
    stage: "3",
    group: "Functions",
    summary:
      "Screening, scheduling, onboarding, policy assistant, employee self-service, training, and workforce analytics. HR spends time on people — not unread CVs and scavenger-hunt forms.",
    body: "You receive recruitment automation, candidate screening, interview scheduling, employee onboarding, an HR assistant, a policy assistant, employee self-service, training systems, and workforce analytics. Who it helps: HR teams whose CVs sit unread while good people take other jobs, and staff who cannot find the leave or policy answer. After go-live employees use self-service for the journeys you scoped; hiring decisions stay with your managers. We do not make a legally binding employment decision. Screening is a draft for humans to review. Workforce analytics are not a medical or psychological diagnosis.",
    capabilities: [
      "Screening and scheduling so good people are not lost in a pile",
      "Onboarding that is not a scavenger hunt",
      "Policy answers staff can find themselves",
      "Workforce analytics for planning — not a clinical file",
      "Managers still own the hire",
    ],
  },
  {
    slug: "finance-ai",
    n: "24",
    name: "AI Finance",
    title: "Invoices, cash, and board packs move without retyping every line",
    stage: "3",
    group: "Functions",
    summary:
      "Invoice and expense automation, reporting, cash-flow, budgets, document intelligence, and management packs. Finance checks exceptions instead of every line.",
    body: "You receive invoice automation, expense processing, financial reporting, cash-flow analytics, budget monitoring, financial document intelligence, an AI finance assistant, and management reporting. Who it helps: controllers whose invoices wait in email and whose cash position is known only after a painful spreadsheet. After go-live packs move faster; journal posts and payments still follow your dual control. This is not investment advice or a substitute for a licensed accountant where the law requires one. We do not promise a close date. Extraction is not claimed at 100% on every scan.",
    capabilities: [
      "Invoices and expenses that do not sit in one inbox",
      "Cash and budgets watched before the month is lost",
      "Document intelligence for the packs you name",
      "An assistant that drafts — a person who posts",
      "Dual control on money stays yours",
    ],
  },
  {
    slug: "procurement-ai",
    n: "25",
    name: "AI Procurement",
    title: "Request to payment with a trail — urgent buying stops being the habit",
    stage: "3",
    group: "Functions",
    summary:
      "Request, approval, vendor, purchase order, delivery, invoice, payment — plus vendor, price, contract, pattern, and spend signals. The same item stops being bought at three prices.",
    body: "You receive automation of Request → Approval → Vendor → Purchase Order → Delivery → Invoice → Payment, plus AI that helps analyse vendors, prices, contracts, purchasing patterns, spending, and risk. Who it helps: procurement and finance leads whose urgent purchases skip approval and whose delivery never matches the order. After go-live the trail is in the system; your approvers still approve. Vendor risk signals are for your owner — not a guarantee a supplier will not fail. We do not replace your legal contract review.",
    capabilities: [
      "A P2P path with who approved what, and when",
      "Vendor and price comparison before the habit of urgency",
      "Delivery and invoice matched to the order",
      "Spend and pattern views for your owner",
      "Risk flags — not a promise a vendor never fails",
    ],
  },
  {
    slug: "workflow-rpa",
    n: "26",
    name: "Workflow & RPA",
    title: "Email stops being your workflow — systems and people share one path",
    stage: "1",
    group: "Automation",
    summary:
      "Automated workflows connecting email, forms, databases, CRM, ERP, WhatsApp, APIs, AI, and human approvals. This is often where customers see the first measurable saving.",
    body: "You receive automated workflows that connect the systems you name and keep a human approval where it matters. Who it helps: teams whose work stops when one person is away, or who use email as a workflow tool and lose things. After go-live there is proof of who approved what, and when. We combine RPA for copy-paste with AI judgement only where you allow it. We do not invent a cycle-time SLA. ROI is measured on the process you scoped — not a global percentage we made up.",
    capabilities: [
      "Cross-system workflows instead of copy-paste",
      "Human approvals where compliance needs them",
      "RPA for the repetitive steps, AI only where you allow it",
      "A trail when someone is away",
      "Savings measured on the process you named",
    ],
  },
  {
    slug: "digital-experience",
    n: "27",
    name: "Digital Experience",
    title: "Websites and kiosks where people complete the task",
    stage: "1",
    group: "Experience",
    summary:
      "Corporate sites, enterprise and customer portals, interactive experiences, kiosks, self-service, and accessibility — so the web is not only a brochure.",
    body: "You receive corporate websites, enterprise portals, customer portals, AI-aware sites, interactive experiences, digital kiosks, self-service systems, and accessibility improvements that were scoped. Who it helps: organisations whose site looks finished but customers cannot complete a simple task, and people blocked by missing accessibility. After go-live the public uses the URL or kiosk you publish. Accessibility is work we scope — not a badge we invent. We do not sell surveillance kiosks. Back-office links are part of the design so the counter is not a dead end.",
    capabilities: [
      "Sites and portals that complete a task",
      "Kiosks and self-service tied to back-office systems",
      "Interactive experiences you can operate",
      "Accessibility improvements that were in the programme",
      "No brochure-only rebuild sold as transformation",
    ],
  },
  {
    slug: "intelligent-websites",
    n: "28",
    name: "AI-Powered Websites",
    title: "The site greets, captures, books, and opens a ticket — then lands in CRM",
    stage: "1",
    group: "Experience",
    summary:
      "Not “we make websites.” You get an Intelligent Digital Experience Platform: on-site assistant, lead capture, CRM, personalization, knowledge search, booking, accounts, and automated support.",
    body: "REVNCIA does not sell generic websites. You receive an Intelligent Digital Experience Platform: AI assistant, lead capture, CRM integration, personalization, analytics, knowledge search, appointment booking, customer accounts, and automated support. Who it helps: owners whose site collects no leads, or whose leads never reach CRM, and visitors who leave because they cannot find an answer. After go-live the assistant and forms write into the CRM in scope. Support does not have to start with a phone number in the footer. We do not promise a conversion rate. Content and knowledge stay yours to approve.",
    capabilities: [
      "An on-site assistant visitors can actually use",
      "Leads that reach CRM",
      "Knowledge search instead of a wall of pages",
      "Booking, accounts, and a ticket — not only a form",
      "Analytics on what visitors did — not a vanity rebuild",
    ],
  },
  {
    slug: "managed-ai",
    n: "29",
    name: "Managed AI Services",
    title: "After go-live, someone still owns quality, cost, and the knowledge base",
    stage: "2",
    group: "Recurring",
    summary:
      "Monitoring, model and cost optimization, security watch, prompt and knowledge updates, usage analytics, and improvement — on a monthly cadence. AI left alone usually gets worse.",
    body: "Instead of delivering AI and leaving, you can receive ongoing operations: AI monitoring, model optimization, cost optimization, security monitoring, prompt optimization, knowledge updates, performance monitoring, usage analytics, system maintenance, and improvement. Who it helps: owners whose project went live and then quietly decayed. After go-live you keep a named owner on your side; we report by the channel in the operations schedule. This is not a 24/7 guaranteed SLA unless a later contract says so. We do not invent a status-page URL here. Human REVNCIA correspondence is email-first from the published Cheyenne office on ordinary US business days.",
    capabilities: [
      "A named operating cadence after the project team leaves",
      "Cost and quality watched together",
      "Prompts and knowledge updated as the business changes",
      "Usage analytics your owner can read",
      "No invented five-minute SLA unless a later contract says so",
    ],
  },
  {
    slug: "ai-governance",
    n: "30",
    name: "AI Governance",
    title: "Rules, logs, and human checks so AI can be explained",
    stage: "2",
    group: "Trust",
    summary:
      "Policies, usage controls, risk assessment, authorization, model and data governance, audit trails, evaluation, and responsible AI frameworks — for enterprise and government.",
    body: "You receive AI policies, usage controls, risk assessment, authorization, model governance, data governance, audit trails, human oversight, evaluation, and responsible AI frameworks. Who it helps: boards and public bodies that will ask what AI is allowed to decide, and teams using public tools with private data. After go-live more assistants can be added without starting a new risk project from zero. This becomes more important as you deploy more AI. We do not replace your legal counsel. Evaluation sets and retirement criteria are part of assurance — not a marketing badge.",
    capabilities: [
      "A written policy for what AI may decide",
      "Usage controls and authorization",
      "Audit trails when something goes wrong",
      "Human oversight on high-impact paths",
      "A framework you can show an auditor",
    ],
  },
  {
    slug: "academy",
    n: "31",
    name: "REVNCIA AI Academy",
    title: "Leaders and staff learn the same language for AI risk and value",
    stage: "5",
    group: "Academy",
    summary:
      "Corporate, government, executive, and employee training — AI, automation, transformation, and governance. Courses, contracts, certifications, and subscriptions are how this is bought.",
    body: "You can receive corporate, government, executive, and employee AI training; automation courses; digital transformation courses; and AI governance training. Who it helps: organisations that buy tools before teams know how to use them safely, and public staff left to learn from random videos. After a course you keep the materials named in the contract. You buy this as courses, corporate contracts, certifications, or subscriptions. We do not sell a degree or a regulated professional licence unless a later accredited programme exists. Fear and rumour should not fill the gap where training belongs.",
    capabilities: [
      "Executive and employee training on the same vocabulary",
      "Government AI training that names risk and value",
      "Automation and transformation courses you can schedule",
      "Governance and certification paths in the contract",
      "No invented university degree",
    ],
  },
  {
    slug: "consulting",
    n: "32",
    name: "REVNCIA Consulting",
    title: "A roadmap before software — what stays human, what it may cost, what could go wrong",
    stage: "1",
    group: "Advisory",
    image: "/images/docs-ai.png",
    summary:
      "Where to deploy AI, what to automate, what remains human, which systems to modernize, the shape of cost and risk. You leave with an AI Transformation Roadmap you can take to a board.",
    body: "You receive executive AI strategy: where AI should be deployed, what should be automated, what should remain human, what systems need modernization, what AI may cost, what ROI can be expected, and what risks exist. Deliverable: AI Transformation Roadmap. Who it helps: leaders whose projects start with software instead of a clear problem. After the engagement you keep the document — you do not need a platform login for this layer. Workshops and interviews are with your people. Cost and ROI in the roadmap are scenarios, not a public price or a headline package.",
    capabilities: [
      "A written sequence you can take to a board",
      "A clear line: automate vs keep human",
      "Which systems to modernize first",
      "Cost, ROI, and risk as scenarios — not a public price card",
      "You keep the document",
    ],
  },
  {
    slug: "audits",
    n: "33",
    name: "Digital Transformation Audits",
    title: "A maturity picture, gaps, and a 12–36 month map — a first step for large buyers",
    stage: "1",
    group: "Advisory",
    summary:
      "A formal look at people, process, technology, data, AI, and security. Output: current state, maturity score, opportunities, gaps, ROI opportunities, and a 12 / 24 / 36-month roadmap.",
    body: "You receive a formal assessment of people, process, technology, data, AI, and security. Output: current-state assessment, digital maturity score, automation and AI opportunities, technology and security gaps, ROI opportunities, and a 12/24/36-month roadmap. Who it helps: large buyers who do not know how mature they really are, and who spend on the loudest vendor instead of the biggest gap. After the audit you have a map — not only a pile of ideas. The score is our method for this engagement, not a regulator’s certificate. We do not invent a public league table of your organisation.",
    capabilities: [
      "A current-state picture leadership can argue from",
      "Maturity scoring for this engagement — not a public ranking",
      "Opportunity and gap maps",
      "Security and technology holes named before an incident",
      "A 12 / 24 / 36-month sequence",
    ],
  },
  {
    slug: "command-center",
    n: "34",
    name: "REVNCIA Command Center",
    title: "One executive view — and the ability to ask why a number moved",
    stage: "5",
    group: "Platform",
    image: "/images/scene-command.png",
    summary:
      "Revenue, customers, operations, AI activity, people, finance, risk, alerts, KPIs, and forecasts — plus investigative questions on data you authorised. Five dashboards become one conversation.",
    body: "Executives see revenue, customers, operations, AI activity, employee productivity, sales, finance, risks, alerts, KPIs, and forecasts. They can ask why a number moved in a period; the system investigates authorised data and explains the answer. Who it helps: leadership that still cannot explain a drop, and owners who cannot govern AI spend because activity is invisible. After go-live alerts need an owner you name. This is a premium offering for leadership that needs a live picture of the organisation. Example charts are not a quote. We do not promise a live picture of systems we were never connected to.",
    capabilities: [
      "One view of money, customers, operations, and AI use",
      "Alerts with an owner — not a noisy inbox",
      "Forecasts and risk on data you authorised",
      "Investigative Q&A: why did this move?",
      "Spend on AI that can actually be governed",
    ],
  },
  {
    slug: "digital-workforce",
    n: "35",
    name: "REVNCIA Digital Workforce",
    title: "Named AI workers with limits — not a pile of one-off bots",
    stage: "5",
    group: "Platform",
    image: "/images/scene-workforce.png",
    summary:
      "Sales, Support, Finance, HR, Operations, Research, and Executive agents — each inside defined permissions and workflows. When a person is off, there is still a named “who does this work.”",
    body: "Instead of selling individual automation, you can commission named AI employees: REVNCIA Sales Agent, Support Agent, Finance Agent, HR Agent, Operations Agent, Research Agent, Executive Agent. Each operates within defined permissions and workflows. Who it helps: organisations where every team built a one-off bot nobody else can reuse, or where permissions are too wide. After go-live humans still oversee; money and legal effect stay under your rules. We do not sell an unsupervised workforce. Agents cannot see what you did not grant.",
    capabilities: [
      "Named functional agents you can introduce to staff",
      "Permissioned workflows — not a wide-open bot",
      "Human oversight written in",
      "A reusable operating model instead of one-off scripts",
      "A clear owner when a person is away",
    ],
  },
  {
    slug: "industry-solutions",
    n: "36",
    name: "REVNCIA Industry Solutions",
    title: "A pack for your sector so you are not buying a brand-new custom project",
    stage: "5",
    group: "Platform",
    summary:
      "REVNCIA for Banks, Governments, Universities, Healthcare, Retail, NGOs, and Enterprises — repeatable delivery kits. Buyers can compare a pack, not only a long proposal.",
    body: "You receive packaged industry solutions so every sale is not a fully custom project: REVNCIA for Banks, Governments, Universities, Healthcare, Retail, NGOs, and Enterprises. Who it helps: buyers who cannot compare a clear pack, and delivery teams whose lessons never become a product for the next client. After go-live you still get the facilities in the statement of work — the pack is a starting kit, not a promise that every module is live on day one. Healthcare packs stay administrative. Banking packs do not replace your licence. Government packs do not make REVNCIA a public authority.",
    capabilities: [
      "A named pack for banks, government, campus, healthcare admin, retail, NGO, or enterprise",
      "Repeatable delivery instead of a blank custom project",
      "Lessons from one client become a kit for the next",
      "A starting scope you can compare — then we write the SOW",
      "Sector limits still apply (admin healthcare, partner cyber)",
    ],
  },
];

export function offeringBySlug(slug: string) {
  return offerings.find((o) => o.slug === slug);
}

export const stages = [
  {
    id: "1",
    title: "Stage 1 — Customers feel it first",
    text: "Voice, WhatsApp, service desks, CRM follow-up, intelligent sites, documents, and a written plan — the work that stops missed calls and unread files.",
  },
  {
    id: "2",
    title: "Stage 2 — You keep running it",
    text: "The AI Gateway: assistants, agents, knowledge, memory, usage and cost controls, analytics, and someone still operating after go-live.",
  },
  {
    id: "3",
    title: "Stage 3 — The backbone leadership trusts",
    text: "CRM, ERP, data, workflow, identity, and cloud on the same governed layer — reports that can go to a board.",
  },
  {
    id: "4",
    title: "Stage 4 — Citizens and sectors",
    text: "Government, education, healthcare administration, finance, retail, and mission programmes with measures you choose to publish.",
  },
  {
    id: "5",
    title: "Stage 5 — One operating layer",
    text: "Command Center, named digital workers, industry packs, and academy — an intelligent layer connecting people, organisations, software, AI, and public-impact services.",
  },
] as const;

export const engagement = [
  { layer: "Consulting", cadence: "A roadmap you keep" },
  { layer: "Implementation", cadence: "A working facility in your environment" },
  { layer: "SaaS", cadence: "Monthly access your staff log into" },
  { layer: "Managed AI", cadence: "We stay after go-live" },
  { layer: "Usage / API", cadence: "Meters you agree before launch" },
] as const;

export const flywheel = [
  "A clear customer problem",
  "AI · automation · clean data",
  "A platform your staff log into",
  "CRM · ERP · AI on one layer",
  "Named digital workers with limits",
  "Numbers you can show",
  "Someone still operates it",
  "The same model in the next site",
] as const;
